services:
  - type: web
    name: crypto-telegram-bot
    runtime: python
    region: oregon
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python crytopay.py
    pythonVersion: 3.10.12
    envVars:
      - key: ENV
        value: "production"
